### ISSUE TITLE
Ramdisk boot after creating files. 

### ISSUE THREAD

**Issue by Stokes83** [Bonkeyzz/SSHRD_Ramdisk_Creator#1]
bro does it work on ios16

**Comment by Bonkeyzz** [comment]
Should work as long as the firmware keys are available online.

If they're not, you have to install iOS 16 on your device and create an iOS 16 ramdisk with gaster as the decryption method.

**Comment by Stokes83** [comment]
I have tried I come across errors when try create command you put as an example. 

How do I install requirements, how do create ramdisk files please better & easy commands will help bro

**Comment by Bonkeyzz** [comment]
> I have tried I come across errors when try create command you put as an example. 
> 
> How do I install requirements, how do create ramdisk files please better & easy commands will help bro 

Can you give me an output of the errors your getting?

to install the requirements you do **while in the cloned repo directory**:
```
pip install -r requirements.txt
```

**Comment by Stokes83** [comment]
Hi bro,

I get these errors:


Please can you assist

**Comment by Bonkeyzz** [comment]
> Hi bro,
> 
> I get these errors:
> 
> 
> Please can you assist 
> Sent from my iPhone
> 
> > On 25 Oct 2022, at 07:44, Joseph R. ***@***.***> wrote:
> > 
> > ﻿
> > I have tried I come across errors when try create command you put as an example.
> > 
> > How do I install requirements, how do create ramdisk files please better & easy commands will help bro
> > 
> > Can you give me an output of the errors your getting?
> > 
> > to install the requirements you do while in the cloned repo directory:
> > 
> > pip install -r requirements.txt
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you authored the thread.
> 

I uh... i don't see any errors...? Can you send me the console output when you try to create a ramdisk?

**Comment by Bonkeyzz** [comment]
The script is updated, please follow the steps to setup again and let me know if it works.

**Comment by Stokes83** [comment]
now on the module requests. i have tried install all when i run (./create script) it says no module found) how do i fix that.

**Comment by Bonkeyzz** [comment]
Please give me the console log when you try to run the script. If you've done `pip install -r requirements.txt` it should have worked.

**Comment by ICH525** [comment]
the main thing is firmware keys to work for ios16... isn't there anyway to get firmware key for ios16?
