### ISSUE TITLE
Iphone 8 keep getting error on almost all ios versions [Failed to get IvKey for BuildID: "18H17". Aborting.]

### ISSUE THREAD

**Issue by kenkit** [Bonkeyzz/SSHRD_Ramdisk_Creator#2]
```./create_ssh_ramdisk.py -d 0 -c 0x8015 -m d201ap -pt iPhone10,4 -i 14.8```

**Comment by Bonkeyzz** [comment]
Keys should now be obtained! Please check again and let me know if it works, i don't have a mac at the moment or a linux VM set up to check myself.

**Comment by Bonkeyzz** [comment]
The version you're trying to build a ramdisk on does not seem to be supported by iBoot64Patcher. Tool is updated to not allow versions below iOS 15.
